### ISSUE TITLE
GCC V12 fix

### ISSUE THREAD

**Issue by prosper00** [cjacker/ch32v003evt_gcc_makefile#1]
with regards to "NOTE: ch32v003 is rv32ec, do not use riscv-gcc v12.0 and above now due to the changes of riscv -march of gcc.":

see [here](https://www.eevblog.com/forum/microcontrollers/risc-v-compilation-errors-mismatched-libgcc/ )- the solution seems to be to compile with "-march=rv32ec_zicsr" , but passing "--march=rv32ec" to the linker

**Comment by prosper00** [comment]
(though I'll note that I see little difference between the WCH GCC version, and v12. The resulting code and code density are essentially the same)

**Comment by cjacker** [comment]
Sorry for late reply.

Tested with xpack 14.2.0 toolchain, '-march=rv32ec_zicsr' now works.
